export const AUTH_ERROR_CODES = [
    "EMAIL_ALREADY_REGISTERED",
    "INVALID_CREDENTIALS",
    "EMAIL_NOT_VERIFIED",
    "EMAIL_ALREADY_VERIFIED",
    "INVALID_VERIFICATION_CODE",
    "VERIFICATION_CODE_EXPIRED",
    "VERIFICATION_ATTEMPTS_EXCEEDED",
    "VERIFICATION_RESEND_RATE_LIMITED",
    "PASSWORD_RESET_TOKEN_INVALID",
    "PASSWORD_RESET_TOKEN_EXPIRED",
    "WORKSPACE_SLUG_UNAVAILABLE",
    "ONBOARDING_STEP_NOT_ALLOWED",
    "INVITATION_NOT_FOUND",
    "INVITATION_INVALID",
    "INVITATION_EXPIRED",
    "INVITATION_ALREADY_ACCEPTED",
    "INVITATION_REVOKED",
    "INVITATION_EMAIL_MISMATCH",
    "INVITATION_ALREADY_EXISTS",
    "MEMBERSHIP_ALREADY_EXISTS",
] as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[number];